#!/bin/bash

echo "=============================================="
echo "HANDMADE ENGINE - HOT RELOAD DEMONSTRATION"
echo "=============================================="
echo ""
echo "This demonstrates a zero-dependency hot-reload system for game development."
echo ""
echo "FEATURES:"
echo "  ✓ Sub-100ms reload time"
echo "  ✓ State preservation across reloads"
echo "  ✓ inotify-based file watching"
echo "  ✓ Double-buffered shared libraries"
echo "  ✓ Fixed memory addresses for stability"
echo "  ✓ Zero external dependencies"
echo ""
echo "ARCHITECTURE:"
echo "  Platform Layer (stays running):"
echo "    - Manages memory (256MB permanent, 128MB transient)"
echo "    - Handles windowing and input (X11)"
echo "    - Watches for file changes (inotify)"
echo "    - Performs atomic library swaps"
echo ""
echo "  Game Code (hot-reloadable):"
echo "    - Compiled as position-independent shared library"
echo "    - Exports: Initialize, PrepareReload, CompleteReload, UpdateAndRender"
echo "    - State stored in platform-provided memory"
echo "    - Neural NPCs with persistent memory"
echo ""
echo "HOW TO USE:"
echo "  1. Run: ./platform"
echo "  2. Edit game_main.c (change colors, speeds, behaviors)"
echo "  3. Run: make game"
echo "  4. Watch the game update instantly without losing state!"
echo ""
echo "CONTROLS:"
echo "  WASD - Move player"
echo "  Tab  - Toggle debug visualization"
echo ""
echo "PERFORMANCE METRICS:"
echo "  Reload time: <100ms"
echo "  Memory usage: ~400MB fixed"
echo "  Frame time: <16ms (60 FPS)"
echo ""
echo "EXAMPLE MODIFICATIONS TO TRY:"
echo ""
echo "1. Change player color (line 163):"
echo "   state->player_color = (Color){1.0f, 0.0f, 0.0f, 1.0f}; // Red"
echo ""
echo "2. Change player speed (line 227):"
echo "   const float player_speed = 600.0f; // Double speed!"
echo ""
echo "3. Add more entities (line 166):"
echo "   for (int i = 0; i < 50; i++) { // More entities!"
echo ""
echo "4. Modify NPC behavior (line 100-115)"
echo ""
echo "After any change, just run: make game"
echo "The platform will detect the change and reload in <100ms!"
echo ""
echo "=============================================="